### PR TITLE
limit number of rows

### PR DESCRIPTION
**Pull request by iAmrSalman**

### CODE REVIEW

**Comment by IPOSDai** [comment]
Why I get the version that is 1.4.0?

**Comment by iAmrSalman** [comment]
> Why I get the version that is 1.4.0?

I am sorry @IPOSDai I don't understand what version?

**Comment by IPOSDai** [comment]
> > Why I get the version that is 1.4.0?
> 
> I am sorry @IPOSDai I don't understand what version?

NO `maximumRowsCount` property,  pod 'TagListView', '1.4.0'

**Comment by iAmrSalman** [comment]
> 
> NO `maximumRowsCount` property: pod 'TagListView', '1.4.0'

Okay @IPOSDai  this pull request didn't get merge yet (hopefully it does 🤞) 

But for time being if you want to use this, you just use my fork instead
 simply replace `pod 'TagListView', '1.4.0'` with `pod 'TagListView', :git => "https://github.com/iAmrSalman/TagListView"`.

But remember to switch back once this pull request is merged.

**Comment by IPOSDai** [comment]
Okay, Thanks .

**Pull request closed without merging**
