### PR TITLE
add force horizontal scroll support

### PR DESCRIPTION
**Pull request by trevorwang**
#39

### CODE REVIEW

**Comment by xhacker** [comment]
It worked great, but I’d like to to keep the scroll view outside of this library. Can you rename the property to `singleLineMode` and remove the scroll view? If the user wanted to scroll they could add TagListView inside a scroll view.

**Comment by xhacker** [comment]
Also, we can add the scroll view in the demo app, but not the library itself.

**Comment by xhacker** [comment]
Another more generic approach would be implementing something like `UILabel`’s `numberOfLines` (as requested in #51).

**Comment by Alex293** [comment]
Hi
What is the state of this ? I really need single line mode, scrolling. It works already by adding a scrollview but if I pin the edges of the tagListView to the scroll view it create more space. Is there a way to go or should I use @trevorwang repo/pr ?

**Comment by viktorwillmann** [comment]
I need the singleLineMode too, what is the current state? Can you please add the horizontal scrolling to the demo as you proposed?

**Comment by trevorwang** [comment]
@Alex293 @viktorwillmann   
Here's the quick way to use this singleLine scroll feature
https://github.com/trevorwang/TagListView/tree/add_horizental_scroll_support

**Comment by aleene** [comment]
If I understand it right, this solution adds a UIScrollView inside the TagListView. And then puts all the TagViews in that UIScrollView in a single row.

I do not see right away what the advantages and disadvantages of this solution are with respect to the solution I proposed #39. It makes TagListView more complex than necessary.

**Comment by viktorwillmann** [comment]
I like the fork, it works good but I need to be able to add a textfield to the end of it, because I want to add an AddTag function by typing a text and pressing return.

**Comment by aleene** [comment]
Any editing support should be part of another pull request.

**Pull request closed without merging**
